name = Subpage
description = Subpage layout.
template = subpage-layout

; ========================================
; Regions
; ========================================
regions[navigation] = Navigation
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/subpage/subpage.layout.css
stylesheets[all][] = css/layouts/subpage/subpage.no-query.layout.css
